CREATE TABLE IF NOT EXISTS spells (
  id SERIAL PRIMARY KEY,
  userguid UUID NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  range VARCHAR(255) NOT NULL DEFAULT '',
  effecton VARCHAR(255) NOT NULL DEFAULT '',
  lastfor INTEGER NOT NULL DEFAULT 0,
  damage INTEGER NOT NULL DEFAULT 0,
  effectto VARCHAR(255) NOT NULL DEFAULT '',
  imageid INTEGER NULL,
  soundid INTEGER NULL,
  ispublic BOOLEAN NOT NULL DEFAULT FALSE,
  createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMP NOT NULL DEFAULT NOW()
);
