CREATE TABLE IF NOT EXISTS potions (
  id SERIAL PRIMARY KEY,
  userguid UUID NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  type VARCHAR(50) NOT NULL DEFAULT 'health',
  effectto VARCHAR(255) NOT NULL DEFAULT 'HP',
  effecttime INTEGER NOT NULL DEFAULT 0,
  effectnumber INTEGER NOT NULL DEFAULT 0,
  value INTEGER NOT NULL DEFAULT 0,
  imageid INTEGER NULL,
  soundid INTEGER NULL,
  ispublic BOOLEAN NOT NULL DEFAULT FALSE,
  createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMP NOT NULL DEFAULT NOW()
);
