CREATE TABLE IF NOT EXISTS curses (
  id SERIAL PRIMARY KEY,
  userguid UUID NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  effectto VARCHAR(255) NOT NULL DEFAULT 'HP',
  effectto2 VARCHAR(255) NULL,
  effect VARCHAR(255) NOT NULL DEFAULT '',
  damage INTEGER NOT NULL DEFAULT 0,
  lastfor INTEGER NOT NULL DEFAULT 0,
  imageid INTEGER NULL,
  soundid INTEGER NULL,
  ispublic BOOLEAN NOT NULL DEFAULT FALSE,
  createdat TIMESTAMP NOT NULL DEFAULT NOW(),
  updatedat TIMESTAMP NOT NULL DEFAULT NOW()
);
