ALTER TABLE pcs RENAME COLUMN movmenteconomy TO actioneconomy;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS mind INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS stamina INTEGER NOT NULL DEFAULT 0;
