ALTER TABLE pcs ADD COLUMN IF NOT EXISTS ring1itemid INTEGER;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS ring2itemid INTEGER;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS ring3itemid INTEGER;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS ring4itemid INTEGER;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS ring5itemid INTEGER;
ALTER TABLE pcs ADD COLUMN IF NOT EXISTS necklaceitemid INTEGER;
