import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import path from 'node:path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const app = express();
app.use(cors());
app.use(express.json());


import * as userController from './controllers/userController';
import * as dungonController from './controllers/dungonController';
import * as tresherController from './controllers/tresherController';
import * as monsterController from './controllers/monsterController';
import * as imageController from './controllers/imageController';
import * as pcController from './controllers/pcController';
import * as friendController from './controllers/friendController';
import * as spellController from './controllers/spellController';
import * as potionController from './controllers/potionController';
import * as curseController from './controllers/curseController';
import * as itemController from './controllers/itemController';
import * as soundController from './controllers/soundController';
app.get('/users/:id', userController.getUser);
app.post('/users', userController.createUser);
app.post('/login', userController.loginUser);
app.get('/users', userController.getAllUsers);
app.put('/users/:id', userController.updateUserFlags);
app.get('/dungons', dungonController.getDungons);
app.get('/dungons/published', dungonController.getPublishedDungons);
app.get('/dungons/sample', dungonController.getSampleDungon);
app.get('/dungons/admin-published', dungonController.getAdminPublishedDungons);
app.get('/dungons/:id', dungonController.getDungonById);
app.post('/dungons', dungonController.createDungon);
app.put('/dungons/:id/metadata', dungonController.updateDungonMetadata);
app.put('/dungons/:id/dungonjson', dungonController.updateDungonJson);
app.put('/dungons/:id/publish', dungonController.publishDungon);
app.put('/dungons/:id/approve', dungonController.approveDungon);
app.put('/dungons/:id/set-sample', dungonController.setSampleDungon);
app.post('/dungons/:id/start', dungonController.startGameFromPublishedDungon);
app.get('/games', dungonController.getGamesForUser);
app.get('/games/sample-session', dungonController.getSampleGameSession);
app.get('/games/:id', dungonController.getGameById);
app.put('/games/:id/save', dungonController.saveGame);
app.delete('/games/:id', dungonController.deleteGame);
app.get('/treshers', tresherController.getTreshers);
app.post('/treshers', tresherController.createTresher);
app.put('/treshers/:id', tresherController.updateTresher);
app.get('/monsters', monsterController.getMonsters);
app.post('/monsters', monsterController.createMonster);
app.put('/monsters/:id', monsterController.updateMonster);
app.get('/images/by-ids', imageController.getPublicImagesByIds);
app.get('/images', imageController.getImages);
app.post('/images', imageController.uploadImageMiddleware, imageController.createImage);
app.put('/images/:id', imageController.updateImage);
app.get('/pcs', pcController.getPcs);
app.post('/pcs', pcController.createPc);
app.get('/pcs/sample', pcController.getSamplePcs);
app.get('/pcs/admin-all', pcController.getAdminPcs);
app.put('/pcs/:id', pcController.updatePc);
app.put('/pcs/:id/set-sample', pcController.setSamplePc);
app.patch('/pcs/:id/award-sp', pcController.awardSpToPc);
app.get('/friends', friendController.getFriends);
app.post('/friends', friendController.createFriend);
app.get('/spells', spellController.getSpells);
app.post('/spells', spellController.createSpell);
app.put('/spells/:id', spellController.updateSpell);
app.get('/potions', potionController.getPotions);
app.post('/potions', potionController.createPotion);
app.put('/potions/:id', potionController.updatePotion);
app.get('/curses', curseController.getCurses);
app.post('/curses', curseController.createCurse);
app.put('/curses/:id', curseController.updateCurse);
app.get('/items', itemController.getItems);
app.post('/items', itemController.createItem);
app.put('/items/:id', itemController.updateItem);
app.get('/sounds', soundController.getSounds);
app.post('/sounds', soundController.uploadSoundMiddleware, soundController.createSound);
app.put('/sounds/:id', soundController.updateSound);
app.use('/images', express.static(path.resolve(__dirname, '../../public/images')));
app.use('/sounds', express.static(path.resolve(__dirname, '../../public/sounds')));

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server running on http://localhost:${port}`);
});
