import { Key } from '../key';
import { Square } from '../square';
import { Cheater } from './cheater';
import { StartPoint } from './start-point';
import { Tresher } from './tresher';
import { TresherPlacement } from './tresher-placement';
import { DungonExit } from './dungon-exit';
import { Monster } from './monster';
import { MonsterPlacement } from './monster-placement';
import { SquareText } from './square-text';
import { FloorTrapPlacement } from './floor-trap-placement';
import { PortalPlacement } from './portal-placement';
import { ItemPlacement } from './item-placement';
import { PotionPlacement } from './potion-placement';
import { SpellPlacement } from './spell-placement';
import { ObstaclePlacement } from './obstacle-placement';

export interface DungonJsonPayload {
  filledSquares: Record<string, true>;
  squares: Record<string, Square>;
  keyList: Key[];
  cheater: Cheater;
  startpoint: StartPoint | null;
  tresherList: Tresher[];
  tresherPlacements: TresherPlacement[];
  monsterList?: Monster[];
  monsterPlacements?: MonsterPlacement[];
  exits?: DungonExit[];
  exitList?: DungonExit[];
  tresherPlacementList?: TresherPlacement[];
  trasherPlacements?: TresherPlacement[];
  monsters?: Monster[];
  monsterPlacementList?: MonsterPlacement[];
  squareTexts?: SquareText[];
  floorTrapPlacements?: FloorTrapPlacement[];
  portalPlacements?: PortalPlacement[];
  itemPlacements?: ItemPlacement[];
  potionPlacements?: PotionPlacement[];
  spellPlacements?: SpellPlacement[];
  floorItemList?: Array<{ id: number; name: string; description: string; type: string; effectValue: number; damage: number; range: number; armorSlot: string | null; effectOn: string | null; isTwoHanded: boolean }>;
  floorPotionList?: Array<{ id: number; name: string; description: string; effectTo: string; effectAmount: number; lastFor: number }>;
  obstaclePlacements?: ObstaclePlacement[];
}
